# Generated by Django 6.0.5 on 2026-06-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrendMart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
